package(default_visibility = ['//visibility:public'])

load("//tools/avrdude:avrdude.bzl", "avrdude")

filegroup(
  name = 'avrdude',
  srcs = [
    'avrdude_x86_64-linux.static',
  ],
)

filegroup(
  name = 'avrdude_config',
  srcs = [
    'avrdude.conf',
  ],
)

